### ISSUE TITLE
iOS 11 - Live Streaming?

### ISSUE THREAD

**Issue by oynek** [luisiam/homebridge-foscamcamera#52]
Just to be clear at this: Will live streaming ever be supported again?

**Comment by mriksman** [comment]
This plugin uses 'homebridge-foscam-stream', which does not support SRTP. The best way would probably be to replace the 'handleStreamRequest' and 'prepareStream' (and any dependent code) from 'homebridge-camera-ffmpeg' which has the required SRTP support.

Until a coder carries out this replacement (use 'homebridge-camera-ffmpeg' instead of 'homebridge-foscam-stream' for the video streaming part), then all I can suggest is to use 'homebridge-camera-ffmpeg' for the streaming part. Ignore the camera created by this plugin, or comment out the line that creates the camera service.

For 'homebridge-camera-ffmpeg' ensure to use this source settings;
`"source": "-rtsp_transport tcp -re -i rtsp://`
Using `-rtsp_transport tcp` fixed the constant stop/start (stuttering/pausing) on Raspberry Pi.

**Comment by echamberlain** [comment]
I submitted a PR https://github.com/luisiam/homebridge-foscamcamera/pull/61 that replaces `homebridge-foscam-stream` with `homebridge-camera-ffmpeg`.

**Comment by pbassham** [comment]
Awesome. Been looking forward to getting this working for a while now.

**Comment by luisiam** [comment]
#61
